DROP TABLE IF EXISTS ENTITY_ID;
CREATE TABLE ENTITY_ID
(
    id    INTEGER AUTO_INCREMENT PRIMARY KEY,
    field VARCHAR(250) NOT NULL
);

DROP TABLE IF EXISTS ENTITY;
CREATE TABLE ENTITY
(
    id    INTEGER PRIMARY KEY,
    field VARCHAR(250) NOT NULL
);
